"""Public OpenAlex source adapter."""

from research_platform.sources.openalex.connector import (
    OpenAlexAccessDeniedError,
    OpenAlexConnector,
    OpenAlexConnectorError,
    OpenAlexEndpointUnavailableError,
    OpenAlexFormatError,
    OpenAlexManifestError,
    OpenAlexNetworkError,
    OpenAlexPayloadStream,
    OpenAlexSizeLimitError,
    OpenAlexTimeoutError,
    OpenAlexTruncatedError,
    PublicConnectivityResult,
)
from research_platform.sources.openalex.manifest import parse_openalex_works_manifest
from research_platform.sources.openalex.metadata import OpenAlexAssetMetadata, unique_assets
from research_platform.sources.openalex.profile_models import (
    EvidenceType,
    FieldProfile,
    OpenAlexDecompressionError,
    OpenAlexEmptySourceError,
    OpenAlexMalformedJSONLError,
    OpenAlexMalformedParquetError,
    OpenAlexProfileError,
    OpenAlexProfileLimitError,
    OpenAlexProfileRun,
    OpenAlexSizeMismatchError,
    OpenAlexSourceProfile,
    OpenAlexUnsupportedFormatError,
    ProfilingLimits,
    RepresentationEvidence,
)
from research_platform.sources.openalex.sample import (
    OpenAlexSampleSelection,
    SkippedOpenAlexAsset,
    select_openalex_works_sample,
)

__all__ = [
    "EvidenceType",
    "FieldProfile",
    "OpenAlexAssetMetadata",
    "OpenAlexDecompressionError",
    "OpenAlexEmptySourceError",
    "OpenAlexMalformedJSONLError",
    "OpenAlexMalformedParquetError",
    "OpenAlexPayloadStream",
    "OpenAlexProfileError",
    "OpenAlexProfileLimitError",
    "OpenAlexProfileRun",
    "OpenAlexSizeMismatchError",
    "OpenAlexSourceProfile",
    "OpenAlexUnsupportedFormatError",
    "ProfilingLimits",
    "RepresentationEvidence",
    "OpenAlexAccessDeniedError",
    "OpenAlexConnectorError",
    "OpenAlexEndpointUnavailableError",
    "OpenAlexFormatError",
    "OpenAlexManifestError",
    "OpenAlexNetworkError",
    "OpenAlexSizeLimitError",
    "OpenAlexTimeoutError",
    "OpenAlexTruncatedError",
    "OpenAlexSampleSelection",
    "OpenAlexConnector",
    "SkippedOpenAlexAsset",
    "PublicConnectivityResult",
    "parse_openalex_works_manifest",
    "select_openalex_works_sample",
    "unique_assets",
]
